{ pkgs }:
[
  pkgs.acpi
  pkgs.adw-gtk3
  pkgs.adwaita-icon-theme
  pkgs.bat
  pkgs.bat-extras.batdiff
  pkgs.bat-extras.batgrep
  pkgs.bat-extras.batman
  pkgs.bat-extras.batpipe
  pkgs.beeper
  pkgs.brightnessctl
  pkgs.clang
  pkgs.cryptsetup
  pkgs.delta
  pkgs.eza
  pkgs.firefox
  pkgs.font-awesome
  pkgs.fzf
  pkgs.gh
  pkgs.git
  pkgs.go
  pkgs.grim
  pkgs.gvfs
  pkgs.htop
  pkgs.imv
  pkgs.inter-nerdfont
  pkgs.kitty
  pkgs.libnotify
  pkgs.mako
  pkgs.mpv
  pkgs.neovim
  pkgs.newsboat
  pkgs.obsidian
  pkgs.pavucontrol
  pkgs.pfetch
  pkgs.pinentry
  pkgs.playerctl
  pkgs.pulseaudio
  pkgs.python3
  pkgs.slurp
  pkgs.sound-theme-freedesktop
  pkgs.sway
  pkgs.swaybg
  pkgs.swaylock
  pkgs.telegram-desktop
  pkgs.thunderbird
  pkgs.tmux
  pkgs.udisks
  pkgs.unzip
  pkgs.wl-clipboard
  pkgs.wofi
  pkgs.xdg-utils
  pkgs.xfce.thunar
  pkgs.yt-dlp
  pkgs.zoxide
  pkgs.zsh
  pkgs.zsh-vi-mode
]
