#!/usr/bin/env bash
# Ensure script runs with bash even if invoked as `sh setup.sh`
if [ -z "$BASH_VERSION" ]; then
  exec /usr/bin/env bash "$0" "$@"
fi
set -euo pipefail

# Colors for output
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Helper to print messages
say() { printf "%b\n" "$1"; }

say "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
say "${BLUE}     Ente Server Setup Wizard${NC}"
say "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
say ""
say "This script will:"
say "  1. Detect existing my-ente directory"
say "     - If present: skip safely (or rename with --rename-existing) and exit"
say "     - If missing: run Ente quickstart to create it"
say "  2. Migrate autogenerated credentials from compose.yaml and museum.yaml"
say "  3. Prompt for domains (no https; ensure DNS A/AAAA records exist)"
say "  4. Save ente-compose.yml and print next steps"
say ""

read -r -p "Hit [Enter] to begin.. " _
say ""

say "${YELLOW}Step 1: Checking for Ente Installation${NC}"

# Optional flag: --rename-existing
RENAME_EXISTING=${RENAME_EXISTING:-0}
if [[ "${1:-}" == "--rename-existing" ]]; then
  RENAME_EXISTING=1
  shift || true
fi

# Detect existing installation
if [ -f "compose.yaml" ] && [ -f "museum.yaml" ]; then
  if [ "$(basename "$PWD")" = "my-ente" ]; then
    if [ "$RENAME_EXISTING" = "1" ]; then
      ts=$(date +%Y%m%d-%H%M%S)
      newname="my-ente.backup-$ts"
      cd ..
      mv my-ente "$newname"
      say "${YELLOW}Renamed existing my-ente to ${newname}. Exiting as requested.${NC}"
      exit 0
    else
      say "${RED}my-ente already exists here. Skipping to avoid overwriting.${NC}"
      say "Pass --rename-existing to rename and exit, or remove it manually."
      exit 0
    fi
  else
    say "${GREEN}[OK] Using current directory: $(pwd)${NC}"
  fi
elif [ -d "my-ente" ]; then
  if [ "$RENAME_EXISTING" = "1" ]; then
    ts=$(date +%Y%m%d-%H%M%S)
    newname="my-ente.backup-$ts"
    mv my-ente "$newname"
    say "${YELLOW}Renamed existing my-ente to ${newname}. Exiting as requested.${NC}"
    exit 0
  else
    say "${RED}my-ente already exists. Skipping to avoid overwriting.${NC}"
    say "Pass --rename-existing to rename and exit, or remove it manually."
    exit 0
  fi
else
  say "my-ente directory not found here, running Ente quickstart..."
  say ""
  # Run the Ente quickstart (auto-answer 'n' to start prompt)
  printf 'n\n' | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ente-io/ente/main/server/quickstart.sh)"
  say ""
  cd my-ente
fi

# Check if we have the required files
if [ ! -f "compose.yaml" ] || [ ! -f "museum.yaml" ]; then
  say "${RED}[ERROR] compose.yaml and museum.yaml not found${NC}"
  say "Please make sure you're in the my-ente directory"
  exit 1
fi

say "${YELLOW}Step 2: Fetching .env template${NC}"
if [ -f .env ]; then
  cp .env .env.bak
  say "Backed up existing .env to .env.bak"
fi
if [ -f .env.example ]; then
  cp .env.example .env
  say "Copied .env.example to .env"
else
  if curl -fsSL https://raw.githubusercontent.com/polarhive/dots/main/hosts/pina/.env.example -o .env.example; then
    cp .env.example .env
    say "Downloaded .env.example and copied to .env"
  else
    # Create empty .env if no template exists locally or remotely
    : > .env
    say "No .env.example available remotely; creating fresh .env"
  fi
fi

# Extract from compose.yaml (portable BSD/GNU sed)
POSTGRES_PASSWORD=$(sed -n 's/^[[:space:]]*POSTGRES_PASSWORD:[[:space:]]*//p' compose.yaml | head -1)
MINIO_ROOT_USER=$(sed -n 's/^[[:space:]]*MINIO_ROOT_USER:[[:space:]]*//p' compose.yaml | head -1)
MINIO_ROOT_PASSWORD=$(sed -n 's/^[[:space:]]*MINIO_ROOT_PASSWORD:[[:space:]]*//p' compose.yaml | head -1)

# Extract from museum.yaml
MUSEUM_ENCRYPTION_KEY=$(sed -n 's/^[[:space:]]*encryption:[[:space:]]*//p' museum.yaml | head -1)
MUSEUM_HASH_KEY=$(sed -n 's/^[[:space:]]*hash:[[:space:]]*//p' museum.yaml | head -1)
MUSEUM_JWT_SECRET=$(sed -n 's/^[[:space:]]*secret:[[:space:]]*//p' museum.yaml | tail -1)

say "${GREEN}[OK] Extracted credentials from quickstart${NC}"
say ""
# Show extracted values for verification
say "${YELLOW}Extracted Environment Preview${NC}"
say "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
say "MINIO_ROOT_USER=$MINIO_ROOT_USER"
say "MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD"
say "MUSEUM_ENCRYPTION_KEY=$MUSEUM_ENCRYPTION_KEY"
say "MUSEUM_HASH_KEY=$MUSEUM_HASH_KEY"
say "MUSEUM_JWT_SECRET=$MUSEUM_JWT_SECRET"
say ""

say "${YELLOW}Step 4: Configure Your Domains${NC}"
say "We need to set up the domain names for your Ente instance."

say "Note: use a bare hostname (no https). Ensure DNS A/AAAA records point to this server."
read_domain() {
  local prompt="$1"; local def="$2"; local val
  while true; do
    read -r -p "$prompt [$def]: " val
    val=${val:-$def}
    if [[ "$val" =~ ^https?:// ]]; then
      say "Please enter a hostname without http/https."
      continue
    fi
    say "$val"
    return 0
  done
}

ENTE_S3_DOMAIN=$(read_domain "S3 Storage domain" "s3.example.com")
ENTE_API_DOMAIN=$(read_domain "API domain" "api.example.com")
ENTE_PHOTOS_DOMAIN=$(read_domain "Photos domain" "photos.example.com")
ENTE_ALBUMS_DOMAIN=$(read_domain "Albums domain" "albums.example.com")
ENTE_CAST_DOMAIN=$(read_domain "Cast domain" "cast.example.com")
ENTE_EMBED_DOMAIN=$(read_domain "Embed domain" "embed.example.com")
say ""

# Apply collected values into .env
say "${YELLOW}Step 5: Applying configuration to .env${NC}"

# Helper to upsert KEY=VALUE in .env
update_env() {
  local key="$1"; shift
  local val="$1"; shift || true
  local tmp
  tmp=$(mktemp)
  awk -v k="$key" -v v="$val" 'BEGIN{u=0} $0 ~ "^"k"=" {print k"="v; u=1; next} {print} END{if(!u) print k"="v}' .env > "$tmp" && mv "$tmp" .env
}

# Snapshot current .env before applying updates for diff
cp .env .env.before

update_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
update_env MINIO_ROOT_USER "$MINIO_ROOT_USER"
update_env MINIO_ROOT_PASSWORD "$MINIO_ROOT_PASSWORD"
update_env MUSEUM_ENCRYPTION_KEY "$MUSEUM_ENCRYPTION_KEY"
update_env MUSEUM_HASH_KEY "$MUSEUM_HASH_KEY"
update_env MUSEUM_JWT_SECRET "$MUSEUM_JWT_SECRET"
update_env ENTE_S3_DOMAIN "$ENTE_S3_DOMAIN"
update_env ENTE_API_DOMAIN "$ENTE_API_DOMAIN"
update_env ENTE_PHOTOS_DOMAIN "$ENTE_PHOTOS_DOMAIN"
update_env ENTE_ALBUMS_DOMAIN "$ENTE_ALBUMS_DOMAIN"
update_env ENTE_CAST_DOMAIN "$ENTE_CAST_DOMAIN"
update_env ENTE_EMBED_DOMAIN "$ENTE_EMBED_DOMAIN"

# Also set ORIGIN values with https:// prefix for web services
update_env ENTE_PHOTOS_ORIGIN "https://$ENTE_PHOTOS_DOMAIN"
update_env ENTE_API_ORIGIN "https://$ENTE_API_DOMAIN"
update_env ENTE_ALBUMS_ORIGIN "https://$ENTE_ALBUMS_DOMAIN"
update_env ENTE_CAST_ORIGIN "https://$ENTE_CAST_DOMAIN"
update_env ENTE_EMBED_ORIGIN "https://$ENTE_EMBED_DOMAIN"

say "${GREEN}[OK] .env prepared and updated!${NC}"

# Show visual diff of changes to .env
say "${YELLOW}Final .env changes${NC}"
# If files are identical, report and skip diff render
if diff -q .env.before .env >/dev/null 2>&1; then
  say "No changes detected from template (.env unchanged)."
else
  # Colorize diff output: green for additions, red for deletions, blue for hunks
  diff -u .env.before .env 2>/dev/null || true | while IFS= read -r line; do
    case "$line" in
      @@*) say "${BLUE}$line${NC}" ;;
      +++*|---*) say "$line" ;;
      +*) say "${GREEN}$line${NC}" ;;
      -*) say "${RED}$line${NC}" ;;
      *) say "$line" ;;
    esac
  done
fi
rm -f .env.before
say ""

# Download our production compose file
say "${YELLOW}Step 6: Preparing Compose file${NC}"
curl -fsSL https://raw.githubusercontent.com/polarhive/dots/main/hosts/pina/ente-compose.yml -o ente-compose.yml
say "${GREEN}[OK] Saved ente-compose.yml${NC}"
say ""

say "${YELLOW}Step 7: Network Configuration${NC}"
say "${RED}IMPORTANT:${NC}"
say "  • Open ports 80 and 443 on your firewall"
say "  • Configure DNS records to point to your server:"
say ""
say "    • $ENTE_PHOTOS_DOMAIN"
say "    • $ENTE_ALBUMS_DOMAIN"
say "    • $ENTE_CAST_DOMAIN"
say "    • $ENTE_EMBED_DOMAIN"

say ""

say "${YELLOW}Step 8: Start Ente${NC}"
say "When ready, run:"
say ""
pwd
say "${BLUE}docker compose -f my-ente/ente-compose.yml up -d${NC}"
say "Then open your browser to: ${BLUE}https://$ENTE_PHOTOS_DOMAIN${NC}"
say "${GREEN}[DONE] Setup complete!${NC}"
