# environment variables
export BEEPER_USE_WAYLAND="1"
export EDITOR="nvim"
export ELECTRON_OZONE_PLATFORM_HINT="wayland"
export GOPATH="/home/$USER/.local/share/go"
export LESSHISTFILE="-"
export MOZ_ENABLE_WAYLAND="1"
export MOZ_USE_XINPUT2="1"
export PATH="$HOME/.local/share/go/bin:$PATH"
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PNPM_HOME="/home/polarhive/.local/share/pnpm"
export SUDO_PROMPT="[sudo] %p 🗝  "
export TERM=screen-256color
export _JAVA_AWT_WM_NONREPARENTING="1"
export npm_config_cache"=~/.cache/npm"
export npm_config_userconfig="~/.config/npm/config"
export TERM="kitty"